---
title: Matrix of Countries
author: 中山大學管理學院 
date: "`r Sys.time()`"
output: 
  html_document:
    highlight: pygments
    theme: flatly
    css: style.css
---

```{r}
rm(list=ls(all=T))
pacman::p_load(readr, dplyr, ggplot2, stringr, maps, Matrix, d3heatmap)
load("data/X.rdata")
```

```{r}
pat = paste(iso3166$ISOname, collapse="|")
CX = str_extract_all(X$text, regex(pat, ignore.case=TRUE))
N9 = unlist(CX) %>% table %>% sort(dec=T) %>% {.[. > 9]} %>% names
C9 = lapply(CX, match, N9)
df = do.call(rbind, lapply(1:length(C9), function(i) {
  if(length(C9[[i]]) > 0) data.frame(i = i, j = C9[[i]])
  })) 
df = subset(df, complete.cases(df))
df$x = 1
mx = sparseMatrix(i=df$i, j=df$j, x=df$x, dimnames=list(1:10760, N9)) %>% 
  as.data.frame.matrix
A = sapply(split(mx, X$sub), colSums)
```

```{r}
z = table(X$sub) %>% sort(dec=T) %>% names
X$sub = factor(X$sub, levels=z)
table(X$sub)
```

```{r}
X$year = format(X$date, "%Y")
table(X$year)
```

```{r}
mx = sparseMatrix(i=df$i, j=df$j, x=df$x, dimnames=list(1:10760, N9)) %>% 
  as.data.frame.matrix
A = sapply(split(mx, X$sub), colSums)
t(A)
```

```{r}
t(A)[,1:12] %>% as.data.frame.matrix %>% d3heatmap(F,F,col="Greens")
```


```{r}
X$ROV = str_count(X$text, "ROV|ROUV")
```

```{r}
xtabs(ROV ~ year, X)
```

```{r}
xtabs(ROV ~ year, X[mx$Germany > 0,])
```

```{r}
sapply(names(mx)[1:10], function(z){
  xtabs(ROV ~ year, X[mx[,z] > 0 & X$year > 2010,])
  }) %>% t
```



<br><br><br><hr>







