---
title: "雙中心網絡分析"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    theme: default
    css: JH.css
    social: menu
    source_code: embed
    logo: nsysu48.png
    favicon: nsysu48.png
runtime: shiny
---

```{r}
pacman::p_load(shiny,shinyWidgets,shinythemes,flexdashboard)
pacman::p_load(dplyr,visNetwork,reshape2,stringr,DT,threejs,RColorBrewer)
pals16 = c(brewer.pal(12,"Set3"), brewer.pal(4,"Set1"))

load("C6.rdata")
```

詳細設定 {data-icon="fa-cogs"}
=====================================================

Row {data-height=75%}
-----------------------------------------------------
### {data-width=25%}

```{r}
ctag = c('', '')
chooseSliderSkin("Modern")

h6("
選出與一組關鍵詞相關性最高的關鍵字，並對它們進行社會網絡分析，
藉以觀察這兩個中心關鍵詞之間可能存在的關係路徑。
")

hr()
pickerInput(
   inputId = "Z",
   label = "第一核心關鍵詞",
   choices = sort(E$name),
   options = list(`live-search`=T, style="btn-success"),
   selected = "Taiwan"
   )
sliderInput("K1",  "第一個核心的聯結數量",  4, 32,  6, 1)
sliderInput("T.COM", "第一核心公司數量", 0, 149, 6, 1)

hr()
pickerInput(
   inputId = "Y",
   label = "第二核心關鍵詞",
   choices = sort(E$name),
   options = list(`live-search`=T, style="btn-success"),
   selected = "training"
   )
sliderInput("K2",  "第二個核心的聯結數量",  4, 32,  6, 1)
sliderInput("R.COM", "第二核心公司數量", 0, 149, 7, 1)

hr()
sliderInput("Q",  "Qantile",   0, 1,  0.4, 0.01)

prettyRadioButtons(
  "Unit", "共同出現的段落", choices = list("句"=1, "段"=2, "篇"=3),
  selected = 1, inline=T, icon=icon("check"), 
  status="success", animation="jelly")

prettyRadioButtons(
  "Cor", "鏈結強度計算方式", 
  choices = list("Co-Occur"=0, "Corr"=1),
  selected = 1, inline=T, icon=icon("check"), 
  status="success", animation="jelly")

SX = reactive({
  VN = input$VN
  if(is.null(VN)) return(NULL)
  if(length(VN$nodes) > 0) {
    k = VN$nodes[[1]] %>% as.integer
    v = XX$Sent[,k]
    }
  else if(length(VN$edges) > 0) {
    k = strsplit(VN$edges[[1]],"-")[[1]] %>% as.integer
    v = rowSums(XX$Sent[,k]) == 2
  }
  else return(NULL)

  df = S[v,] %>%
    setNames(c('nid','pid','sid','sentence')) %>%
    left_join(cbind(nid = 1:nrow(X), X)) %>%
    arrange(desc(date)) %>% as.data.frame() %>% head(200)

  list(df=df, k=k, v=v)
  })


```

-------------------------------------
### visNetwork {data-width=75%}

```{r}

vis_network = function(){
  vv = CR$Docu[which(E$name %in% c(input$Z,input$Y)),]
  ### vw = CR$Docu[which(E$name %in% input$Y),]
  v1 = CR$Docu[,input$Z == E$name]
  v1[E$class != "ORG"] = -1
  si1 = head(order(-v1), input$T.COM)
  v2 = CR$Docu[,input$Y == E$name]
  v2[E$class != "ORG"] = -1
  si2 = head(order(-v2), input$R.COM)
  si = union(union(union(si1, si2), order(-vv[1,])[1:input$K1]),
             order(-vv[2,])[1:input$K2])
  u = as.integer(input$Unit)
  if(input$Cor=="1") x = CR[[u]][si,si]
  else x = CO[[u]][si,si]
  
  tt = with(E, sprintf(
  "%s: %s(%s,%s,%d)",name[si],tooltip[si],
  class[si], sub_class[si], freq[si])) %>% 
  str_replace(",NA,", ",")
  nodes = data.frame(
    id = si, shape='square',
    label=E$name[si], title=tt,
    group=E$class[si], value=sqrt(E$freq[si]), 
    stringsAsFactors=F)
  nodes$shape[nodes$label %in% c(input$Z,input$Y)] = 'circle'
  
  colnames(x) = rownames(x) = si
  x[lower.tri(x,T)] = 0
  x = subset(melt(x), value > 0)
  links = subset(x, value >= quantile(value, input$Q))
  names(links)[1:2] = c('from','to')
  links$value = sqrt(links$value)
  links$id = paste0(links$from, "-", links$to)
  
  JS1 = "function(vis) {Shiny.onInputChange('VN', vis);}"
  visNetwork(nodes, links, width="100%", height="100%") %>%
    visPhysics("forceAtlas2Based") %>%
    visLegend(width=0.1, stepY=100) %>%
    visEdges(color=list(highlight='pink', opacity=0.35)) %>% 
    visOptions(manipulation=F, highlightNearest=F) %>% 
    visEvents(selectNode=JS1, selectEdge=JS1, 
              deselectNode=JS1, deselectEdge=JS1) %>% 
    visGroups(groupname="COUNTRY", color=pals16[1]) %>% 
    visGroups(groupname="FARM", color=pals16[2]) %>% 
    visGroups(groupname="FINANCE", color=pals16[3]) %>% 
    visGroups(groupname="GOV", color=pals16[4]) %>% 
    visGroups(groupname="INST", color=pals16[5]) %>% 
    visGroups(groupname="KWORD", color=pals16[6]) %>% 
    visGroups(groupname="LOC", color=pals16[7]) %>% 
    visGroups(groupname="ORG", color=pals16[8]) %>% 
    visGroups(groupname="TERM", color=pals16[9]) %>% 
    visGroups(groupname="UINV", color=pals16[10]) %>% 
    visGroups(groupname="VESSEL", color=pals16[11]) %>% 
    visLegend(width=0.1, stepY=100, useGroups=F, addNodes=data.frame(
      label=unique(E$class), shape='square', color=pals16[1:11]))
  }

renderVisNetwork( vis_network() )

```



Row {data-height=30%}
-----------------------------------------------------
### {data-width=40%}
```{r}
renderDataTable({
  id = str_subset(names(input),"^.*rows_selected")
  i = 0
  for(x in id) {
    i = as.integer(input[[x]])
    if(length(i)>0) if(i > 0) break
    }    
  if(length(i)>0) if(i > 0) {
    df = SX()$df[i,]; k = SX()$k
    df$z = paste0('',df$title,': ',df$tx)
    for(j in 1:length(k)) df$z = str_replace_all(
      df$z, regex(paste0('(',E$alias[k[j]],')'), E$ignore[k[j]]),
      paste0(ctag[j], '\\1')
      )
    datatable(
      df[,'z',drop=F],escape=F,rownames=F,
      colnames=c('The Selected Article'),
      extensions=c('Scroller'),
      options=list(scrollY="225px",scrollX=F,paging=F,
                   searching=F,ordering=F,info=F)
      ) %>% 
      formatStyle(columns=0:2, fontSize = '90%')
    }
  })
```

### {data-width=60%}
```{r}
renderDataTable({
  if(!is.null(SX())) {
    k = SX()$k; df = SX()$df[,c('date','sentence')]
    df$z = df$sentence
    cname=sprintf('Recent Co-Accurance (%d): ',nrow(df))
    for(i in 1:length(k)) {
      if(i > 1) cname = paste0(cname, " and ")
      cname = paste0(cname, ctag[i], E$name[k[i]], '')
      df$z = str_replace_all(
      df$z, regex(paste0('(',E$alias[k[i]],')'), E$ignore[k[i]]),
      paste0(ctag[i], '\\1') )
      }
    datatable(
      df[,c('date','z')],escape=F,rownames=F,
      colnames=c('Date', cname),
      extensions=c('Scroller','Select'),
      selection=list(mode='single', selected=c(1), target='row'), 
      options=list(
      scrollY="225px",scrollX=F,paging=F,searching=F,ordering=F,
      select = list(style='single'),info=F 
      )) %>% 
      formatStyle(columns=0:2, fontSize = '90%') 
    } })
```

社會網路圖 {data-icon="fa-share-alt"}
=====================================================
```{r}
renderVisNetwork( vis_network() )
```
